[package]
name = "Arbor"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
hex = "0.4.3"
ratatui = "0.29.0"
tokio = { version = "1.44.2", features = ["full"] }

[workspace.metadata.clippy]
warn = ["clippy::all", "clippy::pedantic", "clippy::nursery"]
